
import javax.swing.JOptionPane;

/*
 * JFCalc.java
 *
 * Created on 2 de Setembro de 2009, 10:45
 */



/**
 *
 * @author  aluno
 */
public class JFCalc extends javax.swing.JFrame {
        char op;
        String temp;
        double num1,num2;
        double resultado;
    /** Creates new form JFCalc */
    public JFCalc() {
        initComponents();
        Visor.setEditable(false);
    }

    private void escolheop(char c) {
        op=c;
       num1 = Double.parseDouble(Visor.getText());
       Visor.setText("");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Visor = new javax.swing.JTextField();
        JBapaga = new javax.swing.JButton();
        JB7 = new javax.swing.JButton();
        JB4 = new javax.swing.JButton();
        JB1 = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        JBlimpa = new javax.swing.JButton();
        JB8 = new javax.swing.JButton();
        JB5 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JBponto = new javax.swing.JButton();
        JBfunc = new javax.swing.JButton();
        JB9 = new javax.swing.JButton();
        JB6 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        JBigual = new javax.swing.JButton();
        JBsinal = new javax.swing.JButton();
        JBdiv = new javax.swing.JButton();
        JBMult = new javax.swing.JButton();
        JBmais = new javax.swing.JButton();
        JBmenos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jPanel1.setFocusCycleRoot(true);
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel1KeyTyped(evt);
            }
        });

        Visor.setFocusable(false);

        JBapaga.setText("Bcks");
        JBapaga.setFocusable(false);

        JB7.setText("7");
        JB7.setFocusable(false);
        JB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB7ActionPerformed(evt);
            }
        });

        JB4.setText("4");
        JB4.setFocusable(false);
        JB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB4ActionPerformed(evt);
            }
        });

        JB1.setText("1");
        JB1.setFocusable(false);
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB0.setText("0");
        JB0.setFocusable(false);
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });
        JB0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JB0KeyTyped(evt);
            }
        });

        JBlimpa.setText("CE");
        JBlimpa.setFocusable(false);

        JB8.setText("8");
        JB8.setFocusable(false);
        JB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB8ActionPerformed(evt);
            }
        });

        JB5.setText("5");
        JB5.setFocusable(false);
        JB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB5ActionPerformed(evt);
            }
        });

        JB2.setText("2");
        JB2.setFocusable(false);
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JBponto.setText(".");
        JBponto.setFocusable(false);
        JBponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBpontoActionPerformed(evt);
            }
        });

        JBfunc.setText("CR");
        JBfunc.setFocusable(false);

        JB9.setText("9");
        JB9.setFocusable(false);
        JB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB9ActionPerformed(evt);
            }
        });

        JB6.setText("6");
        JB6.setFocusable(false);
        JB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB6ActionPerformed(evt);
            }
        });

        JB3.setText("3");
        JB3.setFocusable(false);
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        JBigual.setText("=");
        JBigual.setFocusable(false);
        JBigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBigualActionPerformed(evt);
            }
        });

        JBsinal.setText("-+");
        JBsinal.setFocusable(false);

        JBdiv.setText("/");
        JBdiv.setFocusable(false);
        JBdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdivActionPerformed(evt);
            }
        });

        JBMult.setText("*");
        JBMult.setFocusable(false);
        JBMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMultActionPerformed(evt);
            }
        });

        JBmais.setText("+");
        JBmais.setFocusable(false);
        JBmais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmaisActionPerformed(evt);
            }
        });

        JBmenos.setText("-");
        JBmenos.setFocusable(false);
        JBmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBmenosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Visor, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB0, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBponto, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBigual, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBmais, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBmenos, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JB4, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB5, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB6, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBMult, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBapaga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(JB7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBlimpa, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(JB8, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JBfunc, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(JB9, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JBsinal, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(JBdiv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Visor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBapaga)
                    .addComponent(JBlimpa)
                    .addComponent(JBfunc)
                    .addComponent(JBsinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB7)
                    .addComponent(JB8)
                    .addComponent(JB9)
                    .addComponent(JBdiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB4)
                    .addComponent(JB5)
                    .addComponent(JB6)
                    .addComponent(JBMult))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB1)
                    .addComponent(JB2)
                    .addComponent(JB3)
                    .addComponent(JBmenos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB0)
                    .addComponent(JBponto)
                    .addComponent(JBigual)
                    .addComponent(JBmais))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMultActionPerformed
  escolheop('*');      
}//GEN-LAST:event_JBMultActionPerformed

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
       numerodigitado("0");
    }//GEN-LAST:event_JB0ActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        numerodigitado("1");
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
      numerodigitado("2");
    }//GEN-LAST:event_JB2ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
      numerodigitado("3");
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB4ActionPerformed
     numerodigitado("4");
    }//GEN-LAST:event_JB4ActionPerformed

    private void JB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB5ActionPerformed
     numerodigitado("5");
    }//GEN-LAST:event_JB5ActionPerformed

    private void JB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB6ActionPerformed
      numerodigitado("6");
    }//GEN-LAST:event_JB6ActionPerformed

    private void JB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB7ActionPerformed
      numerodigitado("7");
    }//GEN-LAST:event_JB7ActionPerformed

    private void JB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB8ActionPerformed
       numerodigitado("8");
    }//GEN-LAST:event_JB8ActionPerformed

    private void JB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB9ActionPerformed
        numerodigitado("9");
    }//GEN-LAST:event_JB9ActionPerformed

    private void JBpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBpontoActionPerformed
        numerodigitado(".");
    }//GEN-LAST:event_JBpontoActionPerformed

    private void JBmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmaisActionPerformed
       escolheop('+');
    }//GEN-LAST:event_JBmaisActionPerformed

    private void JBigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBigualActionPerformed
        num2 = Double.parseDouble(Visor.getText());
        
        
        switch(op)
        {
            case '+':
            {
                resultado=num1+num2;
                Visor.setText(String.valueOf(resultado));
                break;
               
                
            }
            case '-':
            {
                resultado=num1-num2;
                Visor.setText(String.valueOf(resultado));
                break;
        }
            case '*':
            {
                resultado=num1*num2;
                Visor.setText(String.valueOf(resultado));
                break;
            }
            case '/':
            {
                resultado=num1/num2;
                Visor.setText(String.valueOf(resultado));
                break;
            }
            
             
        }
    }//GEN-LAST:event_JBigualActionPerformed

        private void JBmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBmenosActionPerformed
              escolheop('-');
        }//GEN-LAST:event_JBmenosActionPerformed

        private void JBdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdivActionPerformed
            escolheop('/');
        }//GEN-LAST:event_JBdivActionPerformed

        private void JB0KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JB0KeyTyped
            // TODO add your handling code here:
        }//GEN-LAST:event_JB0KeyTyped

        private void jPanel1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyTyped
          
                
        }//GEN-LAST:event_jPanel1KeyTyped

        private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
           
        }//GEN-LAST:event_formKeyTyped

        private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
          if(evt.getKeyCode() == evt.VK_NUMPAD0)
          {
              numerodigitado("0");
             
          }else if(evt.getKeyCode()==evt.VK_NUMPAD1)
          {
              numerodigitado("1");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD2)
          {
              numerodigitado("2");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD3)
          {
              numerodigitado("3");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD4)
          {
              numerodigitado("4");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD5)
          {
              numerodigitado("5");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD6)
          {
              numerodigitado("6");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD7)
          {
              numerodigitado("7");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD8)
          {
              numerodigitado("8");
          }else if(evt.getKeyCode()==evt.VK_NUMPAD9)
          {
              numerodigitado("9");
          }else if(evt.getKeyCode()==evt.VK_SUBTRACT)
          {
              escolheop('-');
              
          }else if(evt.getKeyCode()==evt.VK_ADD)
          {
              escolheop('+');
              
          }else if(evt.getKeyCode()==evt.VK_DIVIDE)
          {
              escolheop('/');
              
          }
              
          
        }//GEN-LAST:event_formKeyPressed

        private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
            // TODO add your handling code here:
        }//GEN-LAST:event_jPanel1FocusGained

        private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
           
        }//GEN-LAST:event_formMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCalc().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JB4;
    private javax.swing.JButton JB5;
    private javax.swing.JButton JB6;
    private javax.swing.JButton JB7;
    private javax.swing.JButton JB8;
    private javax.swing.JButton JB9;
    private javax.swing.JButton JBMult;
    private javax.swing.JButton JBapaga;
    private javax.swing.JButton JBdiv;
    private javax.swing.JButton JBfunc;
    private javax.swing.JButton JBigual;
    private javax.swing.JButton JBlimpa;
    private javax.swing.JButton JBmais;
    private javax.swing.JButton JBmenos;
    private javax.swing.JButton JBponto;
    private javax.swing.JButton JBsinal;
    private javax.swing.JTextField Visor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void numerodigitado(String numero) {
        temp = Visor.getText();
        temp = temp + numero;
        Visor.setText(temp);
    }
    
}
