

package Cadastros;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import relatorio.rel_cidade;
import utilitarios.conexao;

/**
 *
 * @author Marcus
 */
public class cad_cidade extends javax.swing.JFrame {
conexao con_cidade;
int navega;
String ordenacao ="nome";
    
    public cad_cidade() {
        initComponents();
        con_cidade = new conexao();
        con_cidade.conecta();
        con_cidade.executaSQL("SELECT * FROM CIDADE ORDER BY "+ordenacao);

      try
       {    
//            con_cidade.result.first();
          preenche_jtable();
          
                        mostra_dados();
                         
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
        
       
      
      
    }



    @Override
    protected void finalize() throws Throwable {
        super.finalize();
        con_cidade.desconecta();
        
    }

    


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_ordenacao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        tf_nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_uf = new javax.swing.JComboBox();
        navega_primeiro = new javax.swing.JButton();
        navega_anterior = new javax.swing.JButton();
        navega_ultimo = new javax.swing.JButton();
        navega_proximo = new javax.swing.JButton();
        bt_gravar = new javax.swing.JButton();
        bt_inserir = new javax.swing.JButton();
        bt_alterar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tf_pesquisar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rb_codigo = new javax.swing.JRadioButton();
        rb_nome = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção de Cadastro de Cidades");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Manutenção de Cadastro de Cidades");

        jLabel2.setText("Codigo.:");

        jLabel3.setText("Nome.:");

        tf_codigo.setEditable(false);

        jLabel4.setText("UF.:");

        cb_uf.setMaximumRowCount(5);
        cb_uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));

        navega_primeiro.setText("<<");
        navega_primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navega_primeiroActionPerformed(evt);
            }
        });

        navega_anterior.setText("<");
        navega_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navega_anteriorActionPerformed(evt);
            }
        });

        navega_ultimo.setText(">>");
        navega_ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navega_ultimoActionPerformed(evt);
            }
        });

        navega_proximo.setText(">");
        navega_proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navega_proximoActionPerformed(evt);
            }
        });

        bt_gravar.setText("Gravar");
        bt_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_gravarActionPerformed(evt);
            }
        });

        bt_inserir.setText("Inserir");
        bt_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inserirActionPerformed(evt);
            }
        });

        bt_alterar.setText("Alterar");
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });

        bt_excluir.setText("Excluir");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        tf_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisarActionPerformed(evt);
            }
        });

        jLabel5.setText("Pesquisar.:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel6.setText("Ordenação:");

        grupo_ordenacao.add(rb_codigo);
        rb_codigo.setText("Código");
        rb_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_codigoActionPerformed(evt);
            }
        });

        grupo_ordenacao.add(rb_nome);
        rb_nome.setSelected(true);
        rb_nome.setText("Nome");
        rb_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rb_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rb_codigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_nome)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jButton1.setText("Filtrar na grade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("gerar Relatorio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(navega_primeiro)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(navega_anterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(navega_proximo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(navega_ultimo))
                                    .addComponent(jButton1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_inserir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_gravar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_excluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bt_alterar)))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {navega_anterior, navega_primeiro, navega_proximo, navega_ultimo});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_alterar, bt_excluir, bt_gravar, bt_inserir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(navega_primeiro)
                    .addComponent(navega_anterior)
                    .addComponent(navega_ultimo)
                    .addComponent(navega_proximo)
                    .addComponent(bt_inserir)
                    .addComponent(bt_gravar)
                    .addComponent(bt_excluir)
                    .addComponent(bt_alterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt_alterar, bt_excluir, bt_gravar, bt_inserir, navega_anterior, navega_primeiro, navega_proximo, navega_ultimo});

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-602)/2, (screenSize.height-489)/2, 602, 489);
    }// </editor-fold>//GEN-END:initComponents

    private void mostra_dados() {
        try
        {
            
            tf_codigo.setText(con_cidade.result.getString("codigo"));
            tf_nome.setText(con_cidade.result.getString("nome"));
            cb_uf.setSelectedItem(con_cidade.result.getString("uf"));
            
            
        }catch(Exception e)
        {
            if(navega==1)
                JOptionPane.showMessageDialog(null, "voce ja esta no ultimo registro");
            else if(navega==2)
                JOptionPane.showMessageDialog(null,"voce ja esta no primeiro registro");
            

            
        }
    }

    private void navega_proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navega_proximoActionPerformed
        try {
            con_cidade.result.next();
            mostra_dados();
            navega=1;
        } catch (SQLException ex) {
        
        }

       
}//GEN-LAST:event_navega_proximoActionPerformed

    private void tf_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisarActionPerformed

            try {
                con_cidade.result.first();
                   String igual ="n";
                 int tamanho = tf_pesquisar.getText().length();

           while(igual.equals("n"))
           {
               String pesquisado = con_cidade.result.getString("nome").substring(0,tamanho);

               if(pesquisado.equals(tf_pesquisar.getText()))
               {
                   igual ="s";
               }
               else
               {
                   con_cidade.result.next();
               }


           }


                 tf_codigo.setText(con_cidade.result.getString("codigo"));
                 mostra_dados();
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }



       {

       }
}//GEN-LAST:event_tf_pesquisarActionPerformed

    private void navega_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navega_anteriorActionPerformed
        try {
            con_cidade.result.previous();
            mostra_dados();
            navega=2;
        } catch (SQLException ex) {
            
        }
       
    }//GEN-LAST:event_navega_anteriorActionPerformed

    private void navega_primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navega_primeiroActionPerformed
    try {
            con_cidade.result.first();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "nao foi possivel ir para o primeiro registro"+ex);
        }
       mostra_dados();
    }//GEN-LAST:event_navega_primeiroActionPerformed

    private void navega_ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navega_ultimoActionPerformed
       try {
            con_cidade.result.last();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "nao foi possivel ir para o ultimo registro"+ex);
        }
       mostra_dados();
    }//GEN-LAST:event_navega_ultimoActionPerformed

    private void bt_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inserirActionPerformed
        try
        {
            con_cidade.result.last();
            tf_codigo.setText("");
            tf_nome.setText("");
            tf_nome.requestFocus();
            cb_uf.setSelectedIndex(0);

        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_bt_inserirActionPerformed

    private void bt_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_gravarActionPerformed
        try
        {
            if(tf_nome.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null, "campo nome nao pode ser vazio ");
                return;

            }else if(tf_codigo.getText().length() != 0)
            {
                JOptionPane.showMessageDialog(null,"campo codigo ainda contem valor\n clique em inserir antes de gravar" );
                return;
            }
            else
            {
            con_cidade.executaUpdate("INSERT INTO CIDADE(nome,uf) VALUES('"+tf_nome.getText()+"'"+", "+"'"+cb_uf.getSelectedItem()+"'"+")");
            JOptionPane.showMessageDialog(null, "cidade gravada com Sucesso");
            

            }

            con_cidade.executaSQL("SELECT * FROM CIDADE ORDER BY "+ordenacao);
            con_cidade.result.first();
            mostra_dados();
            preenche_jtable();
             

        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "nao foi possivel gravar dado");
        }

    }//GEN-LAST:event_bt_gravarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        try
        {
            
            int escolha = JOptionPane.showConfirmDialog(null, "excluir cidade "+tf_nome.getText(),"exclusão", JOptionPane.YES_NO_OPTION);

            if(escolha == JOptionPane.YES_OPTION)
            {
                con_cidade.executaSQL("select * from cidade where codigo="+tf_codigo.getText());
            con_cidade.result.first();
                con_cidade.sta.executeUpdate("DELETE FROM CIDADE WHERE codigo ="+tf_codigo.getText());
                JOptionPane.showMessageDialog(null, "cidade excluida com sucesso");
                

            }
            else
           return;

            con_cidade.executaSQL("SELECT * FROM CIDADE ORDER BY "+ordenacao);
            
            con_cidade.result.first();
                
                mostra_dados();
            preenche_jtable();


        
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }



    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        try
        {
            con_cidade.sta.executeUpdate("UPDATE CIDADE SET NOME='"+tf_nome.getText()+"'"+" ,"+"UF='"+cb_uf.getSelectedItem()+"' "+"WHERE CODIGO="+tf_codigo.getText());
            JOptionPane.showMessageDialog(null, "atualização realizada com Sucesso");
            con_cidade.executaSQL("SELECT * FROM CIDADE ORDER BY "+ordenacao);
           
            con_cidade.result.first();
            mostra_dados();
            preenche_jtable();
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_bt_alterarActionPerformed

    private void rb_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_codigoActionPerformed
            ordena_visualizacao("codigo");
    }//GEN-LAST:event_rb_codigoActionPerformed

    private void rb_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_nomeActionPerformed
      ordena_visualizacao("nome");
    }//GEN-LAST:event_rb_nomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        con_cidade.executaSQL("SELECT * FROM CIDADE WHERE NOME LIKE '%"+tf_pesquisar.getText()+"%' ORDER BY "+ordenacao);
        preenche_jtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       rel_cidade r = new rel_cidade();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void preenche_jtable()
    {
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTable2.getColumnModel().getColumn(1).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(2).setPreferredWidth(20);

        DefaultTableModel modelo = (DefaultTableModel)jTable2.getModel();
        modelo.setNumRows(0);
        try
        {
            

            while(con_cidade.result.next())
            {
                modelo.addRow(new Object[]{con_cidade.result.getString("codigo"), con_cidade.result.getString("nome"), con_cidade.result.getString("uf")});
            
            }
            con_cidade.result.first();



        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }


    public void ordena_visualizacao(String ordem)
    {
        ordenacao = ordem;

        try
        {
            con_cidade.executaSQL("SELECT * FROM CIDADE ORDER BY "+ordenacao);
            con_cidade.result.first();
            mostra_dados();

            preenche_jtable();

        }catch(SQLException e)
        {
            JOptionPane.showMessageDialog(rootPane, e);
        }


    }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cad_cidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_gravar;
    private javax.swing.JButton bt_inserir;
    private javax.swing.JComboBox cb_uf;
    private javax.swing.ButtonGroup grupo_ordenacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton navega_anterior;
    private javax.swing.JButton navega_primeiro;
    private javax.swing.JButton navega_proximo;
    private javax.swing.JButton navega_ultimo;
    private javax.swing.JRadioButton rb_codigo;
    private javax.swing.JRadioButton rb_nome;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_pesquisar;
    // End of variables declaration//GEN-END:variables

}
